[features]
report_metadata = false
report_mime = false
mask_highlights = false
send_notice = false
history = false

[parameters]
url_limit = 10
user_agent = "Mozilla/5.0"
accept_lang = "en"
command_channel = "#youtubearchive"

[database]
path = ""
type = "in-memory"

[connection]
nickname = "botnick"
nick_password = ""
alt_nicks = ["botnick_"]
username = "botnick"
realname = "botnick"
server = "chat.freenode.net"
port = 6697
password = ""
use_ssl = true
encoding = "UTF-8"
channels = []
user_info = "Feed me URLs."
source = "https://github.com/video-archivist/youtube-irc-bot"
ping_time = 180
ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15
should_ghost = false
